### PR TITLE
Fix GET /users

### PR DESCRIPTION
**Pull request by pbochis**
* only return users which were invited by the company the current user represents

### CODE REVIEW

**Comment by flowlo** [comment]
Why not have this behaviour opt-in? So that you can get the users that were invited by your company by specify some query parameter?

**Comment by pbochis** [comment]
That's a good point, but in this PR i modify the endpoint which fetches the data for app/candidates. And imo that should be the expected behaviour for that.

**Comment by flowlo** [comment]
bear in mind that although `coduno/app` is the only frontend we currently have, we should not design the API specifically for that, but to be useful generally. `getUsers(...)` is called from `controllers.User(...)` which in turn is wired to `/users`. Limiting this to list users that were invited by your company by default is somewhat unexpected, I figure. We could for example make this `/company/candidates` (or even `/company/{key}/candidates`), which would carry much more context. I think a query parameter is needed if we stick with `/users`, but I'd really prefer having a more explicit endpoint for that.

**Comment by pbochis** [comment]
#129 Implements this.

**Pull request closed without merging**
